-- Migration: 004_add_user_roles
ALTER TABLE users ADD COLUMN IF NOT EXISTS role VARCHAR(50) DEFAULT 'buyer';
ALTER TABLE users ADD COLUMN IF NOT EXISTS vendor_id TEXT;
ALTER TABLE vendors ADD COLUMN IF NOT EXISTS owner_id UUID REFERENCES users(id) ON DELETE SET NULL;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS customer_id UUID REFERENCES users(id) ON DELETE SET NULL;
